### ISSUE TITLE
css not working in 0.9.2

### ISSUE THREAD

**Issue by mbrevda** [halt-hammerzeit/react-phone-number-input#30]
Since updating to 0.9.2, css seems to be broken:
<img width="312" alt="screen shot 2017-04-18 at 12 05 04 am" src="https://cloud.githubusercontent.com/assets/293004/25104855/b1dfdef4-23ca-11e7-9aa9-2c67630d905c.png">

<details>
<summary>Here is my scss file</summary>

```scss
@import "node_modules/react-phone-number-input/rrui.css";
@import "node_modules/react-phone-number-input/style.css";

.react-phone-number-input__phone {
    width: 220px;
    border-bottom: none;
    padding-left: 15px;
}

.rrui__select__selected {
    border-bottom: none;
}

.signUpPhone {
    display: flex;
    align-items: center;
    padding: 20px;
}
```
</details>

**Comment by halt-hammerzeit** [comment]
What do you mean by "broken" and "not working"

**Comment by mbrevda** [comment]
Sorry for being vague, I should have explained more.

 Previously, the country icon (or globe) would show.
<img width="314" alt="screen shot 2017-04-18 at 12 15 33 am" src="https://cloud.githubusercontent.com/assets/293004/25105191/3e2b2dae-23cc-11e7-878f-5fd99a851053.png">

Also, the autocomplete is not showing the country list:
<img width="734" alt="screen shot 2017-04-18 at 12 16 55 am" src="https://cloud.githubusercontent.com/assets/293004/25105272/8eed7cba-23cc-11e7-90bf-5e3a13d52b8f.png">

**Comment by halt-hammerzeit** [comment]
Well, you can try the demo, it's the latest version
https://github.com/halt-hammerzeit/react-phone-number-input/blob/gh-pages/index.html
Seems to be working.
If you can modify the example so that it doesn't work then I could have a look at it

**Comment by mbrevda** [comment]
The demo works fine. Other than the css changes, is there anything else I would need to change when upgrading?

**Comment by halt-hammerzeit** [comment]
Nothing really.
The code for the select was updated (a bit of refactoring and moving things around) but without a sample project there's not much I could say about your case.

**Comment by mbrevda** [comment]
Thanks. I believe I tracked down the issues:

1. If `country` is set to a blank string, the globe icon is not show, and neither is any flag shown.
2. The autocomplete countries were using the color (black) defined [here](https://github.com/halt-hammerzeit/react-phone-number-input/commit/35576ba877ae8aa38494e44d0c807d8f5b72beb6#diff-3e1a93b11aefa9b36204aaec251b6741). Since this has been removed, the text was defaulting to white (on a white background)

**Comment by halt-hammerzeit** [comment]
1. Yes, `country` should be `undefined` or `null`. I added country validation in the new version.

2. Yes, it `inherit`s color now. Also, I've just spotted that I didn't delete another `color: black` so in the new version this CSS rule is also removed (and is `inherit`ed instead):

```css


.rrui__select--expanded .rrui__select__selected--autocomplete
{
	color: black;
}
```

In the newest version (`0.10.x`) I also refactored `style.css` a bit, with comments.
